services:
  - type: web
    name: synapse-ai-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.onrender.com
    healthCheckPath: /health
    autoDeploy: true
